export const FRAMEWORKS = [
	{ value: 'react', label: 'React' },
	{ value: 'next.js', label: 'Next.js' },
	{ value: 'vue.js', label: 'Vue.js' },
	{ value: 'nuxt.js', label: 'Nuxt.js' },
	{ value: 'angular', label: 'Angular' },
	{ value: 'svelte', label: 'Svelte' },
	{ value: 'sveltekit', label: 'SvelteKit' },
	{ value: 'astro', label: 'Astro' },
	{ value: 'remix', label: 'Remix' },
	{ value: 'express.js', label: 'Express.js' },
	{ value: 'nestjs', label: 'NestJS' },
	{ value: 'django', label: 'Django' },
	{ value: 'flask', label: 'Flask' },
	{ value: 'spring', label: 'Spring' },
	{ value: 'laravel', label: 'Laravel' },
	{ value: 'ruby-on-rails', label: 'Ruby on Rails' },
	{ value: 'wordpress', label: 'WordPress' },
	{ value: 'strapi', label: 'Strapi' },
	{ value: 'keystone', label: 'KeystoneJS' },
];
